rem 3.1_retrain.bat
rem use ckpt in ./pretraind_models generated by pretrain.bat
python ../../ModelTrainer.py ^
  --mode=train_and_eval ^
  --train_file_pattern=./autoannotated_tfrecords/train/*.tfrecord  ^
  --val_file_pattern=./autoannotated_tfrecords/valid/*.tfrecord ^
  --model_name=efficientdet-d0 ^
  --hparams="input_rand_hflip=False,image_size=512x512,num_classes=5,label_map=./label_map.yaml" ^
  --model_dir=./retrained_models ^
  --label_map_pbtxt=./label_map.pbtxt ^
  --eval_dir=./retrain_eval ^
  --ckpt=./pretrained_models  ^
  --train_batch_size=4 ^
  --early_stopping=map ^
  --patience=10 ^
  --eval_batch_size=1 ^
  --eval_samples=400  ^
  --num_examples_per_epoch=800 ^
  --num_epochs=100
